# Generated by Django 4.1.3 on 2023-09-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_and_players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='descriptions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='', upload_to='team'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_and_players.player'),
        ),
    ]
