# Generated by Django 4.1.3 on 2023-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_player', '0004_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='team'),
        ),
    ]
