# Generated by Django 4.1.3 on 2023-12-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_player', '0005_alter_team_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
