# Generated by Django 4.1.3 on 2023-12-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_player', '0006_delete_player'),
        ('users', '0004_alter_userinfo_team_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_team', to='team_player.team'),
        ),
    ]
