# Generated by Django 4.1.3 on 2023-12-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userinfo_phone_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
