# Generated by Django 4.1.3 on 2023-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
