# Generated by Django 4.1.3 on 2023-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygons',
            name='coordinates',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
