# Generated by Django 4.1.3 on 2023-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0003_alter_polygons_descriptions_alter_polygons_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygons',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='polygons',
            name='name',
            field=models.CharField(max_length=50, verbose_name='URL'),
        ),
    ]
