# Generated by Django 4.1.3 on 2023-08-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0004_polygons_slug_alter_polygons_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygons',
            name='slug',
            field=models.SlugField(default=' '),
        ),
    ]
