# Generated by Django 4.1.3 on 2023-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0005_alter_polygons_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygons',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
