# Generated by Django 4.1.3 on 2023-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0007_polygons_image_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygons',
            name='url_yandex',
            field=models.CharField(default='', max_length=500),
        ),
    ]
