# Generated by Django 4.1.3 on 2023-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0009_alter_polygons_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygons',
            name='image',
            field=models.ImageField(blank=True, upload_to='polygons/'),
        ),
        migrations.AlterField(
            model_name='polygons',
            name='image_full',
            field=models.ImageField(blank=True, default='', upload_to='polygons/full'),
        ),
    ]
