# Generated by Django 4.1.3 on 2023-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0010_alter_polygons_image_alter_polygons_image_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygons',
            name='lat',
            field=models.FloatField(default='1.0'),
        ),
        migrations.AddField(
            model_name='polygons',
            name='lon',
            field=models.FloatField(default='1.0'),
        ),
    ]
