# Generated by Django 4.1.3 on 2023-09-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0011_polygons_lat_polygons_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygons',
            name='lat',
            field=models.FloatField(default='39.715209'),
        ),
        migrations.AlterField(
            model_name='polygons',
            name='lon',
            field=models.FloatField(default='47.246355'),
        ),
    ]
