# Generated by Django 4.1.3 on 2023-09-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0012_alter_polygons_lat_alter_polygons_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygons',
            name='coordinates',
        ),
    ]
