# Generated by Django 4.1.3 on 2023-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0013_remove_polygons_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygons',
            name='lat',
            field=models.FloatField(default='47.246355'),
        ),
        migrations.AlterField(
            model_name='polygons',
            name='lon',
            field=models.FloatField(default='39.715209'),
        ),
    ]
