# Generated by Django 4.1.3 on 2023-09-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polygons', '0008_polygons_url_yandex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('date', models.DateField()),
                ('polygon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='games_polygon', serialize=False, to='polygons.polygons')),
                ('descriptions', models.CharField(max_length=500)),
            ],
        ),
    ]
