# Generated by Django 4.1.3 on 2023-09-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polygons', '0008_polygons_url_yandex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('organizer', models.CharField(default='STRIKE61', max_length=50)),
                ('start', models.TimeField(default=None)),
                ('scenario', models.CharField(max_length=500)),
                ('contribution', models.IntegerField(default=200)),
                ('foto_games', models.ImageField(blank=True, upload_to='sunday_games')),
                ('is_future', models.BooleanField(default=True)),
                ('polygon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_polygon', to='polygons.polygons')),
            ],
        ),
    ]
