# Generated by Django 4.1.3 on 2023-09-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='asd',
            field=models.CharField(default='', max_length=12),
        ),
    ]
