# Generated by Django 4.1.3 on 2023-09-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='contribution',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='game',
            name='organizer',
            field=models.CharField(default='STRIKE61', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.TimeField(default=None),
        ),
    ]
