# Generated by Django 4.1.3 on 2023-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0003_remove_game_asd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start',
            field=models.TimeField(default='10:00'),
        ),
    ]
