# Generated by Django 4.1.3 on 2023-09-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0003_game_contribution_game_organizer_game_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='descriptions',
            new_name='scenario',
        ),
    ]
