# Generated by Django 4.1.3 on 2023-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0004_rename_descriptions_game_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='foto_games',
            field=models.ImageField(default='', upload_to='sunday_games'),
        ),
    ]
