# Generated by Django 4.1.3 on 2023-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0005_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='foto_games',
        ),
        migrations.AddField(
            model_name='game',
            name='foto_scenario',
            field=models.ImageField(blank=True, upload_to='sunday_games_scenario'),
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
