# Generated by Django 4.1.3 on 2023-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0005_game_foto_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='foto_games',
            field=models.ImageField(null=True, upload_to='sunday_games'),
        ),
    ]
