# Generated by Django 4.1.3 on 2023-09-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0006_alter_game_foto_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='foto_games',
            field=models.ImageField(blank=True, default=2, upload_to='sunday_games'),
            preserve_default=False,
        ),
    ]
