# Generated by Django 4.1.3 on 2023-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0007_alter_game_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scenario',
            field=models.TextField(max_length=10000),
        ),
    ]
