# Generated by Django 4.1.3 on 2023-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0007_alter_game_foto_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_future',
            field=models.BooleanField(default=True),
        ),
    ]
