# Generated by Django 4.1.3 on 2023-10-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0010_alter_game_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='game_images')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_images', to='sunday_games.game')),
            ],
        ),
    ]
