# Generated by Django 4.1.3 on 2023-10-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0011_gameimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameImage',
        ),
    ]
