# Generated by Django 4.1.3 on 2023-10-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday_games', '0017_alter_game_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scenario',
            field=models.TextField(default='Сценарий будет позже', max_length=10000),
        ),
    ]
